[build]
  command = "npm install"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/subscribed"
  to = "/subscribed.html"
  status = 200

[[redirects]]
  from = "/find-key"
  to = "/find-key.html"
  status = 200
